### ISSUE TITLE
Crash upon .psbt import

### ISSUE THREAD

**Issue by pvesborg** [akhavr/electrum-dash#161]
electrum-dash crashes immediately upon 
Tools -> Load tx -> From file (pick foo.psbt)

Thanks

**Comment by zebra-lucky** [comment]
Can you post some more info, please?
You wallet is software or some HW variant (trezor, ledger, etc...)?
What your operating system?

**Comment by zebra-lucky** [comment]
You can try enable main menu Help -> Automated Crash Reports,
then restart wallet app.

And then after operation crashes window with "Dash Electrum - An Error Occured"
title must appear.

In this window the button "Show report contents" must show more detailed info about a problem.

**Comment by pvesborg** [comment]
Done.
Below is a dump of the "Show report":

Cheers and happy new year
Peter

---
Traceback:

Traceback (most recent call last):

  File "electrum_dash\gui\qt\main_window.py", line 2946, in do_process_from_file

  File "electrum_dash\gui\qt\main_window.py", line 1196, in show_transaction

  File "electrum_dash\gui\qt\transaction_dialog.py", line 86, in
show_transaction

  File "electrum_dash\gui\qt\transaction_dialog.py", line 657, in __init__

  File "electrum_dash\gui\qt\transaction_dialog.py", line 394, in update

  File "electrum_dash\transaction.py", line 784, in estimated_size

  File "electrum_dash\transaction.py", line 818, in estimated_weight

  File "electrum_dash\transaction.py", line 808, in estimated_total_size

  File "electrum_dash\transaction.py", line 740, in serialize_to_network

  File "electrum_dash\transaction.py", line 740, in <genexpr>

  File "electrum_dash\transaction.py", line 737, in create_script_sig

  File "electrum_dash\transaction.py", line 674, in input_script

  File "electrum_dash\transaction.py", line 660, in guess_txintype_from_address

Exception: unrecognized address: '7nvYwMPwjLm9jswxK2fEJdfn3n4hSDdB8w'

Additional Information:


Dash Electrum version: 4.0.4.1
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18)
[MSC v.1900 64 bit (AMD64)]
Operating system: Windows-10-10.0.18362-SP0
Wallet type: standard
Locale: en_GB

**Comment by zebra-lucky** [comment]
Thanks, found a bug in code, please do not reuse address from debug output.

Must be fixed in upcoming release.

**Comment by pvesborg** [comment]
Great that you found the bug!

I wonder what would be the issue re-using such an address regardless of
debug dump being publicly known?  I don't see how that compromises DASH on
this multi-sig address (beyond privacy, obviously). Am I missing something?

Cheers

**Comment by zebra-lucky** [comment]
> I wonder what would be the issue re-using such an address regardless of debug dump being publicly known? I don't see how that compromises DASH on this multi-sig address (beyond privacy, obviously). Am I missing something?

Address info and txid info is private so there is need
to improve code to strip this info from traces in future.

**Comment by pvesborg** [comment]
Tried to load the .psbt again in v. 4.0.9.0.
It still crashes. Now the Traceback is:

Traceback (most recent call last):

  File "electrum_dash\gui\qt\main_window.py", line 2968, in do_process_from_file

  File "electrum_dash\gui\qt\main_window.py", line 1202, in show_transaction

  File "electrum_dash\gui\qt\transaction_dialog.py", line 86, in
show_transaction

  File "electrum_dash\gui\qt\transaction_dialog.py", line 659, in __init__

  File "electrum_dash\gui\qt\transaction_dialog.py", line 395, in update

  File "electrum_dash\transaction.py", line 785, in estimated_size

  File "electrum_dash\transaction.py", line 819, in estimated_weight

  File "electrum_dash\transaction.py", line 809, in estimated_total_size

  File "electrum_dash\transaction.py", line 741, in serialize_to_network

  File "electrum_dash\transaction.py", line 741, in <genexpr>

  File "electrum_dash\transaction.py", line 738, in create_script_sig

  File "electrum_dash\transaction.py", line 678, in input_script

  File "electrum_dash\transaction.py", line 481, in multisig_script

AssertionError: m 0, n 1

**Comment by zebra-lucky** [comment]
Thank for traces!
Need to do more investigations in psbt code.

**Comment by zebra-lucky** [comment]
After some investigations found second trace repeated,
if load psbt transaction from multisig wallet in regular wallet.

Possibly, if this is used for broadcasting, additional signing
is need on multisig and then signed txn can be loaded into regular wallet.

**Comment by zebra-lucky** [comment]
p.s.: found BTC version of wallet allow that operations, so need to found where is problem.
